version: '3.2'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGKILL
    ports:
      - 5000:5000
    depends_on:
      - pg_db
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=guest
      - POSTGRES_USER=guest
      - POSTGRES_DB=databasename

    volumes:
      - ./db/:/var/lib/postgresql/data
    ports:
      - 5432:5432

